[versions]
agp = "8.3.2"
kotlin = "2.1.21"
ksp = '2.1.21-2.0.1'
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
androidx-test-core = "1.6.1"
espressoCore = "3.5.1"
appcompat = "1.6.1"
androidx-room = "2.7.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "junitVersion" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test-core" }
assertj = { group = "org.assertj", name = "assertj-core", version = "3.25.3" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.8.0" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.8.0" }
robolectric = { group = "org.robolectric", name = "robolectric", version = "4.11.1" }
volley = { group = "com.android.volley", name = "volley", version = "1.2.1" }
wordpress-utils = { group = "org.wordpress", name = "utils", version = "3.14.0" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
automatticPublish = { id="com.automattic.android.publish-to-s3", version="0.10.0"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }
