[versions]
agp = "8.10.1"
androidx-appcompat = "1.7.1"
androidx-core = "1.16.0"
androidx-test-espresso = "3.6.1"
androidx-test-ext = '1.2.1'
androidx-test-main = "1.6.2"
assertj = '3.27.3'
automattic-publish = "0.10.0"
eventbus = "3.3.1"
junit = "4.13.2"
kotlin = "2.1.21"
kotlinx-coroutines = '1.10.2'
robolectric = "4.14.1"
volley = "1.2.1"
wordpress-fluxc = "2.76.0"
wordpress-utils = "3.14.0"
wordpress-wellsql = "2.0.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidx-test-main-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-main" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "eventbus" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
wordpress-fluxc-annotations = { group = "org.wordpress.fluxc", name = "fluxc-annotations", version.ref = "wordpress-fluxc" }
wordpress-fluxc-processor = { group = "org.wordpress.fluxc", name = "fluxc-processor", version.ref = "wordpress-fluxc" }
wordpress-utils = { group = "org.wordpress", name = "utils", version.ref = "wordpress-utils" }
wordpress-wellsql-main = { group = "org.wordpress", name = "wellsql", version.ref = "wordpress-wellsql" }
wordpress-wellsql-processor = { group = "org.wordpress.wellsql", name = "wellsql-processor", version.ref = "wordpress-wellsql" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
automattic-publish = { id = "com.automattic.android.publish-to-s3", version.ref = "automattic-publish" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
