[versions]
agp = "8.10.1"
androidx-appcompat = "1.7.1"
androidx-core = "1.16.0"
androidx-room = "2.7.2"
androidx-test-core = "1.6.1"
androidx-test-espresso = "3.6.1"
androidx-test-ext = '1.2.1'
androidx-test-runner = "1.6.2"
assertj = '3.27.3'
automattic-publish = "0.10.0"
jna = "5.17.0@aar"
junit = "4.13.2"
kotlin = "2.1.21"
kotlinx-binary-compatibility-validator = "0.18.0"
kotlinx-coroutines = '1.10.2'
ksp = "2.1.21-2.0.2"
mockwebserver = "3.2.0"
robolectric = "4.14.1"
terl-lazysodium-android = "5.2.0@aar"
turbine = "1.2.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test-core" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
terl-lazysodium-android = { module = "com.goterl:lazysodium-android", version.ref = "terl-lazysodium-android" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
automattic-publish = { id = "com.automattic.android.publish-to-s3", version.ref = "automattic-publish" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-binary-compatibility-validator = { id = 'org.jetbrains.kotlinx.binary-compatibility-validator', version.ref = 'kotlinx-binary-compatibility-validator' }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
